name: 'Retrieve AWS Secrets and Parameters'
description: 'Retrieve secrets and parameters from AWS'
runs:
  using: 'composite'
  steps:
    - name: Retrieve secrets and parameters from AWS
      run: |
        echo "GITHUB_TOKEN=$(aws ssm get-parameter --name /path/to/github_token --with-decryption --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
        echo "AWS_REGION=$(aws ssm get-parameter --name /path/to/aws_region --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
        echo "ECR_REPOSITORY_MAIN=$(aws ssm get-parameter --name /path/to/ecr_repository_main --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
        echo "ECR_REPOSITORY_DEVELOP=$(aws ssm get-parameter --name /path/to/ecr_repository_develop --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
