name: 'Set up Python and Install Dependencies'
description: 'Set up Python and install dependencies with Poetry'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
runs:
  
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install dependencies from pyproject.toml
      run: |
        poetry install
      shell: bash