name: My Composite Workflow
on:
    push:
      branches:
        - main

jobs:
  Source:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout out Repository Code
          uses: actions/checkout@v3
        
  Version:
    runs-on: ubuntu-latest
    needs: Source
    steps:
        - name: Set up Dependencies and Versioning
          uses: ./.github/actions/semantic-release
