name: My Composite Workflow
on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout out Repository Code
          uses: actions/checkout@v3

        - name: Set up Dependencies for Semantic Versioning
          uses: ./.github/actions/semantic-release
