name: BuildSageMakerModel
on:
  push:
    branches:
      - dev
    paths:
      - pipelines/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve AWS Secrets and Parameters
        id: retrieve-secrets
        uses: ./.github/actions/retrieve-aws-secrets

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade . botocore boto3 awscli

  