jobs:
    build:
      needs: release # Depends on the release job
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.9, 3.10, 3.11]
          branch: [ develop]
      container:
        image: ${{ env.AWS_REGION }}.dkr.ecr.amazonaws.com/${{ env.ECR_REPOSITORY_MAIN if github.event.ref == 'refs/heads/main' else env.ECR_REPOSITORY_DEVELOP }}:${{ github.event.release.tag_name }}
        env:
          NODE_ENV: development
      steps:
        - name: Build and Test
          uses: ./.github/actions/build-and-test
          with:
            python-version: ${{ matrix.python-version }}
  